# -*- coding: utf-8 -*-
"""codealpha_stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ilsVR885J9qNuICg6rzVMHHom4I6M3I
"""

stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 2800,
    "AMZN": 3400
}

def calculate_investment():
    total_investment = 0
    portfolio = {}

    while True:
        stock_name = input("Enter stock name (or 'exit' to finish): ").upper()
        if stock_name == 'EXIT':
            break
        if stock_name not in stock_prices:
            print("Stock not found. Please enter a valid stock name.")
            continue

        quantity = int(input(f"Enter quantity for {stock_name}: "))
        portfolio[stock_name] = quantity
        total_investment += stock_prices[stock_name] * quantity

    print("\nYour Portfolio:")
    for stock, qty in portfolio.items():
        print(f"{stock}: {qty} shares at ${stock_prices[stock]} each")
    print(f"Total Investment Value: ${total_investment}")

    save_to_file = input("Do you want to save the results to a file? (yes/no): ").lower()
    if save_to_file == 'yes':
        filename = input("Enter filename (without extension): ")
        with open(f"{filename}.txt", "w") as f:
            f.write("Your Portfolio:\n")
            for stock, qty in portfolio.items():
                f.write(f"{stock}: {qty} shares at ${stock_prices[stock]} each\n")
            f.write(f"Total Investment Value: ${total_investment}\n")
        print(f"Results saved to {filename}.txt")
calculate_investment()

